# Generated by Django 4.1.3 on 2022-11-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'activity_details',
            },
        ),
        migrations.CreateModel(
            name='CameraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'camera_details',
            },
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person_details',
            },
        ),
        migrations.CreateModel(
            name='AnomalyVideoPaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('video_path', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.activitydetails')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.cameradetails')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.persondetails')),
            ],
            options={
                'db_table': 'anomaly_video_paths',
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.activitydetails')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.cameradetails')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.persondetails')),
            ],
            options={
                'db_table': 'activity_record',
            },
        ),
    ]
