# Generated by Django 4.1.3 on 2022-11-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
